from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent

DATASET_NAME = "McAuley-Lab/Amazon-Reviews-2023"
SUBSET = "raw_review_Electronics"
META_SUBSET = "raw_meta_Electronics"

# Default sample used by the exploratory notebooks.
N_SAMPLES = 5_000

# Full precomputed dimensionality-reduction artifacts live here. Keep this
# directory read-only during local experiments.
DIM_REDUCTION_DIR = PROJECT_ROOT / "dim_reduction"
DIM_REDUCTION_RESULTS_DIR = DIM_REDUCTION_DIR / "results"

# Local, laptop-friendly dimensionality-reduction flow. Everything generated by
# scripts/run_small_dim_reduction.py goes under this directory.
SMALL_RESULTS_DIR = DIM_REDUCTION_DIR / "results_small"
SMALL_DATA_DIR = SMALL_RESULTS_DIR / "data"
SMALL_BENCHMARKS_DIR = SMALL_RESULTS_DIR / "benchmarks"
SMALL_COORDINATES_DIR = SMALL_RESULTS_DIR / "coordinates"
SMALL_PLOTS_DIR = SMALL_RESULTS_DIR / "plots"

MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"

METHODS = ["pca", "umap", "pacmap", "fitsne"]
METHOD_LABELS = {
    "pca": "PCA",
    "umap": "UMAP",
    "pacmap": "PaCMAP",
    "fitsne": "FIt-SNE",
}

# Small local benchmark defaults. Override them from the CLI when needed.
SMALL_N_VALUES = [500, 1_000, 2_000, 5_000]
SMALL_MAX_SAMPLES = max(SMALL_N_VALUES)
SMALL_METHODS = METHODS
SMALL_BATCH_SIZE = 32
SMALL_REPEATS = 3
SMALL_TIMING_MODE = "fit-only"
SMALL_WARMUP_SAMPLES = 250

# Keep local visual outputs reproducible. Use --random-state none if you prefer
# maximum UMAP parallelism over deterministic coordinates.
SMALL_RANDOM_STATE = "42"
SMALL_CLUSTER_METHODS = METHODS.copy()
SMALL_MAX_PLOT_POINTS = 20_000
SMALL_MIN_CLUSTER_SIZE = 30
